language: cpp
sudo: false
cache:
  ccache: true
  directories:
    - $HOME/.ccache
env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=200M
    - CCACHE_CPP2=1
    - COMPILER='ccache g++-4.9'
    - TMP_DIR='/tmp'
    - INCLUDE_PATH=$TRAVIS_BUILD_DIR/other_includes
os: linux
dist: trusty
compiler: g++
addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages: 
      - g++-4.9
      - cmake

before_install:
  - mkdir -p ${INCLUDE_PATH}
install:
  - bash ./test/setup/install_dependencies.sh

# install dependencies
before_script:
  - mkdir ./test/test_build
  - cd ./test/test_build
  - export CXX="g++-4.9"
  - cmake ..

script:
  - make
  


#before we run the build
notifications: # set notification options
  email:
    recipients:
      - nguyen.phineas@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: [change]
    on_failure: [change]
    
    # Or we could just enable/disable all email
    email: true